---
## 需要监听的房间号
room_id: 870004

## 需要监听的事件类型 0 为不监听此类
events: # 任意事件触发时，若不为0，会更新 bili_trigger 和 event_id 参数，动画控制器应由 bili_trigger 开始,由 event_id 辨识不同种类事件
  - enter: 0    # 监听进场      1：发送至聊天框“欢迎【用户名】进入直播间”
  - danmaku: 0  # 监听弹幕      1：发送至聊天框“【用户名】说【内容】”
  - emoticon: 0 # 监听表情包    1：发送至聊天框“【用户名】说【表情】”
  - gift: 0     # 监听礼物      1：发送至聊天框“【用户名】赠送【数量】个【礼物名】”  2：更新{gift_id, gift_price, gift_num}参数 3：前两者都做
  - sc: 0       # 监听醒目留言  1：发送至聊天框“【用户名】发送【价格】说【内容】”  2：更新{gift_id, gift_price}参数  3：前两者都做
  - guard: 0    # 监听大航海    1：发送至聊天框“【用户名】开通【数量】个月【大航海等级】” 2：更新{gift_id, gift_price}参数  3：前两者都做



## event_id:
# enter 进场: 0
# danmaku 弹幕: 1
# emoticon 表情包: 2
# gift 礼物: 3
# sc 醒目留言: 4
# guard 大航海: 5

